/**:
  ros__parameters:

    # Topics
    pointCloudTopic: "synced_lidar"           # Point cloud data from sync node
    imuTopic: "synced_imu"                    # IMU data from sync node
    # pointCloudTopic: "unilidar/cloud"           # Point cloud data from sync node
    # imuTopic: "bno055/imu_raw"                    # IMU data from sync node
    odomTopic: "odometry/imu"                  # IMU pre-preintegration odometry, same frequency as IMU
    gpsTopic: "odometry/gpsz"                  # GPS odometry topic from navsat, see module_navsat.launch file

    # Frames
    lidarFrame: "lidar_link"                   # LiDAR frame name
    baselinkFrame: "lidar_link"                     # Robot base frame name
    odometryFrame: "odom"                          # Odometry frame name
    mapFrame: "map"                                # Map frame name

    # GPS Settings
    useImuHeadingInitialization: false           # if using GPS data, set to "true"
    useGpsElevation: false                       # if GPS elevation is bad, set to "false"
    gpsCovThreshold: 2.0                         # m^2, threshold for using GPS data
    poseCovThreshold: 25.0                       # m^2, threshold for using GPS data

    # Export settings
    savePCD: false                               # https://github.com/TixiaoShan/LIO-SAM/issues/3
    savePCDDirectory: "/Downloads/LOAM/"         # in your home folder, starts and ends with "/". Warning: the code deletes "LOAM" folder then recreates it. See "mapOptimization" for implementation

    # Sensor Settings
    sensor: unitree                             # lidar sensor type, either 'velodyne', 'ouster' or 'livox' or 'unitree'
    N_SCAN: 90                                  # number of lidar channels (i.e., Velodyne/Ouster: 16, 32, 64, 128, Livox Horizon: 6)
    Horizon_SCAN: 1964                          # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048, Livox Horizon: 4000)
    downsampleRate: 1                           # Ham nokta bulutunu seyreltme oranı (1 = seyreltme yok). Bu değer arttıkça, nokta bulutunun çözünürlüğü düşer. Feature kayıpları olur, işlem gücü azalır.
    lidarMinRange: 0.5                          # default: 1.0, minimum lidar range to be used
    lidarMaxRange: 10.0                         # default: 1000.0, maximum lidar range to be used
    imu_rate: 100.0                             # IMU frequency in Hz

    # IMU Settings
    imuAccNoise: 0.130                           # IMU accelerometer measurement noise standard deviation (m/s^2)
    imuGyrNoise: 0.200                           # IMU gyroscope measurement noise standard deviation (rad/s)
    imuAccBiasN: 0.001                          # IMU accelerometer bias random walk (m/s^2/sqrt(Hz))
    imuGyrBiasN: 0.00005                        # IMU gyroscope bias random walk (rad/s/sqrt(Hz))
    imuGravity: 9.80665                         # Gravity acceleration
    imuRPYWeight: 0.01                          # Weight for IMU roll pitch yaw

    extrinsicTrans: [ 0.0,  0.0,  -0.04 ]   # IMU'dan LiDAR'a öteleme [x, y, z] (metre). Lütfen bu değerleri kendi ölçümlerinize göre güncelleyin.

    extrinsicRot: [ -1.0,  0.0,    0.0,
                    0.0,   1.0,    0.0,
                    0.0,   0.0,   -1.0 ]

    extrinsicRPY: [ 1.0,  0.0,  0.0,
                    0.0,  1.0,  0.0,
                    0.0,  0.0, 1.0 ]

    # LOAM feature threshold
    edgeThreshold: 1.0                          # Bir noktanın "köşe" olması için gereken minimum eğrilik. Yapısal (bol kenarlı) ortamlarda artırılabilir.
    surfThreshold: 0.1                          # Bir noktanın "yüzey" olması için gereken minimum eğrilik. Ortama göre ayarlanır. Düz duvarların bol olduğu yerlerde azaltılabilir.
    edgeFeatureMinValidNum: 10                  # Minimum geçerli kenar özellikleri sayısı
    surfFeatureMinValidNum: 100                 # Minimum geçerli yüzey özellikleri sayısı

    # voxel filter paprams
    odometrySurfLeafSize: 0.2                    # default: 0.4 - outdoor, 0.2 - indoor
    mappingCornerLeafSize: 0.1                    # default: 0.2 - outdoor, 0.1 - indoor
    mappingSurfLeafSize: 0.2                       # default: 0.4 - outdoor, 0.2 - indoor

    # robot motion constraint (in case you are using a 2D robot)
    z_tollerance: 1000.0                           # meters
    rotation_tollerance: 1000.0                   # radians

    # CPU Params
    numberOfCores: 4                            # number of cores for mapping optimization
    mappingProcessInterval: 0.15                # seconds, regulate mapping frequency

    # Surrounding map
    surroundingkeyframeAddingDistThreshold: 1.0 # meters, regulate keyframe adding threshold
    surroundingkeyframeAddingAngleThreshold: 0.2 # radians, regulate keyframe adding threshold
    surroundingKeyframeDensity: 2.0            # meters, downsample surrounding keyframe poses   
    surroundingKeyframeSearchRadius: 50.0       # meters, within n meters scan-to-map optimization (when loop closure disabled)

    # Loop closure
    loopClosureEnableFlag: true                # Enable/disable loop closure
    loopClosureFrequency: 1.0                  # Hz, regulate loop closure constraint add frequency
    surroundingKeyframeSize: 50                # submap size (when loop closure enabled)
    historyKeyframeSearchRadius: 15.0          # meters, key frame that is within n meters from current pose will be considerd for loop closure
    historyKeyframeSearchTimeDiff: 30.0        # seconds, key frame that is n seconds older will be considered for loop closure
    historyKeyframeSearchNum: 25               # number of history key frames will be fused into a submap for loop closure !!!!!!!!!!
    historyKeyframeFitnessScore: 0.3           # döngü adayının kabul edilmesi için gereken icp eşleme skoru

    # Visualization
    globalMapVisualizationSearchRadius: 1000.0  # meters, global map visualization radius
    globalMapVisualizationPoseDensity: 10.0     # meters, global map visualization keyframe density
    globalMapVisualizationLeafSize: 1.0         # meters, global map visualization cloud density
